// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikmqrlrmvkxdhpkmykxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrbXFybHJtdmt4ZGhwa215a3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTkxNzksImV4cCI6MjA2NzY3NTE3OX0.TxU3mt54pPDT9vchb2vWrh5NU_ZFV81uKx7DCI8KjP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});